import { CanvasWorkspaceData, ViewerMode } from "./types";

const bodyText = {
  root: "A damp corridor crossed the old studio like a sentence that had not decided how to end. The first note on the floor said only one thing: keep walking until the walls begin to remember your name.",
  middle: "Minseo folded the note and slipped it into her sleeve. Light from the broken skylight stopped one step short of the iron door, as if the room beyond preferred visitors who already knew what they were entering.",
  branchA: "She opened the door and found canvases facing the wall, every one of them signed with tomorrow's date. The newest canvas was still wet, and the portrait on it was hers.",
  branchB: "Instead of opening the door, she followed the sound behind the vents and found a narrow stairwell. Halfway down, she realized someone below was reading her thoughts aloud, one line behind her own mind.",
  ending: "When she finally turned around, the studio had already chosen its ending. The portrait was gone, but the paint on her fingertips matched the missing face exactly.",
  auto: "The stairwell ended in a room that looked unfinished only because it expected her to complete it. By the time she understood that, the last empty frame had already learned how to hold her reflection.",
};

export function getMockCanvasWorkspace(
  shareKey: string,
  viewerMode: ViewerMode,
): CanvasWorkspaceData {
  return {
    id: "canvas-mock-1",
    shareKey,
    title: "Relay Story Studio",
    subtitle: "A branching studio mystery written on a shared canvas.",
    viewerMode,
    maxUserNodesPerBranch: 5,
    selectedNodeId: "node-2",
    nodes: [
      {
        id: "node-1",
        title: "Root node",
        excerpt: "The studio corridor waits for the first decision.",
        body: bodyText.root,
        createdBy: "sohee",
        createdAt: "2026-03-11 19:12",
        isEnding: false,
        endingType: null,
        position: { x: 220, y: 280 },
        image: {
          url: "/wireframes/relay-novel-wireframes-board.png",
          alt: "Canvas reference placeholder",
        },
      },
      {
        id: "node-2",
        title: "Node",
        excerpt: "The note is folded away and the iron door waits.",
        body: bodyText.middle,
        createdBy: "yuna",
        createdAt: "2026-03-11 19:20",
        isEnding: false,
        endingType: null,
        position: { x: 520, y: 280 },
      },
      {
        id: "node-3",
        title: "Branch A",
        excerpt: "The studio reveals a portrait dated tomorrow.",
        body: bodyText.branchA,
        createdBy: "jiho",
        createdAt: "2026-03-11 19:33",
        isEnding: false,
        endingType: null,
        position: { x: 860, y: 180 },
      },
      {
        id: "node-4",
        title: "Ending node",
        excerpt: "The portrait chooses the ending first.",
        body: bodyText.ending,
        createdBy: "minji",
        createdAt: "2026-03-11 19:48",
        isEnding: true,
        endingType: "user",
        position: { x: 1180, y: 180 },
      },
      {
        id: "node-5",
        title: "Branch B",
        excerpt: "A voice in the vent speaks a half-step behind her.",
        body: bodyText.branchB,
        createdBy: "dani",
        createdAt: "2026-03-11 19:42",
        isEnding: false,
        endingType: null,
        position: { x: 860, y: 420 },
      },
      {
        id: "node-6",
        title: "Auto ending",
        excerpt: "The branch ends where the final empty frame waits.",
        body: bodyText.auto,
        createdBy: "system",
        createdAt: "2026-03-11 19:59",
        isEnding: true,
        endingType: "auto_limit",
        position: { x: 1180, y: 420 },
      },
    ],
    edges: [
      { id: "edge-1", sourceId: "node-1", targetId: "node-2" },
      { id: "edge-2", sourceId: "node-2", targetId: "node-3" },
      { id: "edge-3", sourceId: "node-3", targetId: "node-4" },
      { id: "edge-4", sourceId: "node-2", targetId: "node-5" },
      { id: "edge-5", sourceId: "node-5", targetId: "node-6" },
    ],
  };
}
